# Generated by Django 6.0.6 on 2026-07-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0007_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.ImageField(null=True, upload_to='posts/images'),
        ),
    ]
